EnterpriseDB/terraform-provider-biganimal

README.md
TODO

chore: cleanup the TODO file, as we already have a CONTRIBUTING.md file

---

GNUmakefile

fixes #28. 
That would be the solution I would propose.

Set OS_ARCH in GNUmakefile

---

.github/workflows/pre-commit.yml

Configure the ci to run pre-commit check at each commit/pr
Will scan only newer files compared to the main branch
close #53

ci: Configure CI pre-commit check

---

.github/workflows/pre-commit.yml

close #80 
Will fix linter issue like [this](https://github.com/EnterpriseDB/terraform-provider-biganimal/actions/runs/3521157296/jobs/5902733897):
```
../../../go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/set/iterator.go:3:17: syntax error: unexpected any, expecting ]
../../../go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/set/iterator.go:8:19: syntax error: unexpected [, expecting comma or )
../../../go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/set/iterator.go:12:19: syntax error: unexpected [, expecting comma or )
../../../go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/set/ops.go:10:12: syntax error: unexpected [, expecting comma or )
../../../go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/set/ops.go:29:12: syntax error: unexpected [, expecting comma or ) …
```

fix: configure the right version of Golang in pre-commit action on  GitHub

---

pkg/provider/resource_cluster.go
pkg/provider/resource_region.go

fix: update delete and create timeout for region and cluster resource

---

examples/README.md

docs: Enhance examples README.md

---

README.md

The provider is published https://registry.terraform.io/providers/EnterpriseDB/biganimal. We don't need some of the hackery here anymore.

docs: Update the README.md

---

CHANGELOG.md
GNUmakefile
README.md
docs/resources/cluster.md
docs/resources/region.md
examples/data-sources/biganimal_cluster/provider.tf
examples/data-sources/biganimal_region/provider.tf
examples/resources/biganimal_cluster/eha/resource.tf
examples/resources/biganimal_cluster/ha/resource.tf
examples/resources/biganimal_cluster/single_node/aws/resource.tf
examples/resources/biganimal_cluster/single_node/azure/resource.tf
examples/resources/biganimal_cluster/single_node/resource.tf
examples/resources/biganimal_region/resource.tf

build: Prepare the repo for 0.2.0 release

---

pkg/api/region_client.go

fix: Increase timeout for Region Client

---

CHANGELOG.md
GNUmakefile
README.md
docs/resources/cluster.md
docs/resources/project.md
docs/resources/region.md
examples/data-sources/biganimal_cluster/provider.tf
examples/data-sources/biganimal_projects/provider.tf
examples/data-sources/biganimal_region/provider.tf
examples/resources/biganimal_cluster/eha/resource.tf
examples/resources/biganimal_cluster/ha/resource.tf
examples/resources/biganimal_cluster/single_node/aws/resource.tf
examples/resources/biganimal_cluster/single_node/azure/resource.tf
examples/resources/biganimal_cluster/single_node/resource.tf
examples/resources/biganimal_project/resource.tf
examples/resources/biganimal_region/resource.tf

build: Prepare the repo for 0.3.0 release

---

.wordlist-en-custom.txt
docs/resources/azure_connection.md
pkg/provider/resource_azure_connection.go

Some checks didn't run while we were reviewing the #144, such as spellchecker. 
That's why I'm creating this PR.

Fix missing checks

---

templates/resources/cluster.md.tmpl
templates/resources/region.md.tmpl

For more details, please visit https://github.com/hashicorp/terraform-plugin-docs/pull/237/

docs: fix the templates so that we don't generate redundant whitespace

---

CHANGELOG.md
README.md
docs/resources/aws_connection.md
docs/resources/azure_connection.md
docs/resources/cluster.md
docs/resources/faraway_replica.md
docs/resources/project.md
docs/resources/region.md
examples/data-sources/biganimal_aws_connection/provider.tf
examples/data-sources/biganimal_cluster/provider.tf
examples/data-sources/biganimal_faraway_replica/provider.tf
examples/data-sources/biganimal_projects/provider.tf
examples/data-sources/biganimal_region/provider.tf
examples/resources/biganimal_aws_connection/resource.tf
examples/resources/biganimal_azure_connection/resource.tf
examples/resources/biganimal_cluster/eha/resource.tf
examples/resources/biganimal_cluster/ha/resource.tf
examples/resources/biganimal_cluster/single_node/aws/resource.tf
examples/resources/biganimal_cluster/single_node/azure/resource.tf
examples/resources/biganimal_cluster/single_node/resource.tf
examples/resources/biganimal_faraway_replica/aws/resource.tf
examples/resources/biganimal_faraway_replica/azure/resource.tf
examples/resources/biganimal_faraway_replica/cluster_and_faraway_replica/resource.tf
examples/resources/biganimal_faraway_replica/resource.tf
examples/resources/biganimal_project/resource.tf
examples/resources/biganimal_region/resource.tf

build: Prepare the repo for 0.4.0 release

---

docs/resources/cluster.md
docs/resources/faraway_replica.md
pkg/provider/resource_cluster.go
pkg/provider/resource_fareplica.go

Define `throughput` field as optional
will close #205

feat: throughput storage field could be configurable

---

CONTRIBUTING.md
DEVELOPMENT.md
GNUmakefile
README.md

* Added a new ./DEVELOPMENT.md file and moved the testing and development related information there. 
* Also added how to use the BigAnimal CLI for easier token management, Fixes #190. 
Please review.

docs: Add development related docs

---

docs/resources/cluster.md
docs/resources/faraway_replica.md
docs/resources/project.md
examples/resources/biganimal_cluster/eha/resource.tf
examples/resources/biganimal_cluster/ha/resource.tf
examples/resources/biganimal_cluster/single_node/aws/resource.tf
examples/resources/biganimal_cluster/single_node/azure/resource.tf
examples/resources/biganimal_cluster/single_node/resource.tf
examples/resources/biganimal_faraway_replica/aws/resource.tf
examples/resources/biganimal_faraway_replica/azure/resource.tf
examples/resources/biganimal_faraway_replica/cluster_and_faraway_replica/resource.tf
examples/resources/biganimal_faraway_replica/resource.tf
examples/resources/biganimal_project/resource.tf

```
pre-commit run tfupdate --all-files
```
Please review.

Update random provider version

---

pkg/provider/resource_cluster.go

For more details, please visit https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/206#issuecomment-1517935195 
Please review.

fix: DiffSuppressFunc for throughput

---

.pre-commit-config.yaml
docs/data-sources/faraway_replica.md
docs/resources/faraway_replica.md

Also docs: Update faraway_replica docs. (those were not updated when we merged #216 )
Please review.

ci: Update .pre-commit-config.yaml

---

DEVELOPMENT.md

Update docs to use the BA CLI v2.0.0 commands. 
Please review.

docs: update docs to use BA CLI v2.0.0

---

CHANGELOG.md
GNUmakefile
README.md
docs/resources/aws_connection.md
docs/resources/azure_connection.md
docs/resources/cluster.md
docs/resources/faraway_replica.md
docs/resources/project.md
docs/resources/region.md
examples/data-sources/biganimal_aws_connection/provider.tf
examples/data-sources/biganimal_cluster/provider.tf
examples/data-sources/biganimal_faraway_replica/provider.tf
examples/data-sources/biganimal_projects/provider.tf
examples/data-sources/biganimal_region/provider.tf
examples/resources/biganimal_aws_connection/resource.tf
examples/resources/biganimal_azure_connection/resource.tf
examples/resources/biganimal_cluster/eha/resource.tf
examples/resources/biganimal_cluster/ha/resource.tf
examples/resources/biganimal_cluster/single_node/aws/resource.tf
examples/resources/biganimal_cluster/single_node/azure/resource.tf
examples/resources/biganimal_cluster/single_node/resource.tf
examples/resources/biganimal_faraway_replica/aws/resource.tf
examples/resources/biganimal_faraway_replica/azure/resource.tf
examples/resources/biganimal_faraway_replica/cluster_and_faraway_replica/resource.tf
examples/resources/biganimal_faraway_replica/resource.tf
examples/resources/biganimal_project/resource.tf
examples/resources/biganimal_region/resource.tf

ci: Prepare for the 0.4.2 release.

---

docs/data-sources/pgd.md

A trivial fix, I don't know how it slipped from our eyes :) 
Let's fix this in a separate PR. 
Please review. (If it's OK for you, please merge right after)

docs: Fix forgotten field for PGD Data source

---

docs/resources/region.md

`make docs` is generating this string now, so let's update our docs as well. 
Please review.

docs: Update the docs for the region resource

---

examples/README.md

To fix the broken link and link the PGD examples.
Please review.

docs: Update examples README.md

---

pkg/plan_modifier/data_group_custom_diff.go

PG version, PG type and Cloud Provider is not allowed to change in the config. Should throw and error and stop if it detects a change

PGD update error fix

---

docs/resources/pgd.md
examples/README.md
examples/resources/biganimal_pgd/gcp/data_group/resource.tf
examples/resources/biganimal_pgd/gcp/data_groups_with_witness_group/resource.tf
templates/resources/pgd.md.tmpl

PGD GCP examples

---

pkg/plan_modifier/data_group_custom_diff.go
pkg/plan_modifier/pg_config.go
pkg/provider/resource_pgd.go

feat: pg config. Insert default values into plan if it doesn't exist

ww-pgd-pg-config-defaults

---

docs/resources/cluster.md
examples/resources/biganimal_cluster/import.sh

docs: Add cluster import example

---

pkg/provider/data_source_cluster.go
pkg/provider/data_source_pgd.go
pkg/provider/resource_cluster.go
pkg/provider/resource_pgd.go
pkg/provider/validators.go

Reviewed and added validations so far:
* Project ID validation
* <s>Supported CSPs validation</s>
* Backup Retention Period Validation. 
* Pg_type validation for cluster resources.
* Cluster_architecture_id validation.
Please review.

Adding and updating validations

---

docs/data-sources/pgd.md
docs/resources/pgd.md
examples/resources/biganimal_pgd/aws/data_groups_with_witness_group/resource.tf
examples/resources/biganimal_pgd/azure/data_groups_with_witness_group/resource.tf
examples/resources/biganimal_pgd/gcp/data_groups_with_witness_group/resource.tf
pkg/models/common/api/maintenance_window.go
pkg/models/common/terraform/maintenance_window.go
pkg/models/pgd/api/witness_group.go
pkg/models/pgd/terraform/witness_group.go
pkg/provider/data_source_pgd.go
pkg/provider/resource_pgd.go

Blocked. REST API fix in progress

feat: maintenance window for pgd witness group

---

pkg/plan_modifier/data_group_custom_diff.go
pkg/provider/resource_pgd.go

pgd groups needs allowed IP ranges fix when private networking is true and when allowed IP ranges is []

fix: pgd allowed ip ranges bug
