EnterpriseDB/terraform-provider-biganimal

- README.md
Provider use BA_API_URI to talk with BigAnimal API. Add the configuration step in README.md
> fix: export BA_API_URI variable

- pkg/models/architecture.go
- pkg/models/cluster.go
fixes https://github.com/EnterpriseDB/terraform-provider-biganimal/issues/18
This re-enables the cluster_architecture property and removes the 'name' field from the model to allow the validations to proceed
merge after https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/15
This PR is actually a clone of https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/19 . I opened a new one, because i mucked up the git history in that branch while trying to sign the commits :)
> fix: send the cluster_architecture in on cluster updates

- pkg/api/cluster_client.go
- pkg/models/cluster.go
- pkg/provider/resource_cluster.go
This is a rework of a previous PR, https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/21 with changes addressed.  new PR, because rewriting the previous prs and commits to use a signed commit mucked up the history.
fixes https://github.com/EnterpriseDB/terraform-provider-biganimal/issues/20
Moves the IsOk() check from the api client to the cluster model, and also includes a check for a 'healthy' phase
merge after #33
> fix: add a check on the cluster phase to make sure changes have been properly manifest

- examples/region_data/data.tf
- examples/region_data/variables.tf
- pkg/models/region.go
fixes #30 
the mapstructure struct tag of the region model was referencing `id`, while the terraform schema was referencing `region_id`.  this PR changes the mapstructure tag to `region_id`
> fix: use region_id instead of 'id' in the region model

- examples/region_data/data.tf
- examples/region_resource/resource.tf
- examples/region_resource/variables.tf
A small change to pass cloud_provider and region_id as the variables when creating region resource.
> fix: change cloud_provider and region_id as the variables

- .github/workflows/spellcheck.yml
- .spellcheck.yaml
- .wordlist-en-custom.txt
This PR adds two checkers:
- spellchecker
- checker for non-inclusive language. 
The `.wordlist-en-custom.txt` file is generated after the output of the spellchecker. 
Please review. 
Related to #42.  Please merge it after merging #49
> ci: Spellcheck GH action

- go.mod
- go.sum
Because we didn't implement Conventional Commits, https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/45 created a non-conventional commit. 
This PR updated the gomega package to the latest version.
> chore(deps): Update gomega to the latest version

- README.md
- pkg/api/api.go
- pkg/provider/provider.go
With this PR, BigAnimal provider block can take arguments. Before, terraform provider wasn't configurable via provider block. 
```hcl
provider "biganimal" {
ba_bearer_token = <redacted> // See Getting and API Token section for details
// ba_api_uri   = "https://portal.biganimal.com/api/v2" // Optional
}
```
* The naming for the provider block arguments and the environment variables are now the same.(before it was `ba_token` for argument and `BA_BEARER_TOKEN` for the env var.  
* I tried to update the README.md, I'm open to suggestions.
* ba_api_uri argument is added as optional, with the default value `"https://portal.biganimal.com/api/v2"`. 
* I would update the examples to include a provider configuration in a separate PR. 
Please review.
> fix: Set ba_bearer_token and ba_api_uri provider arguments

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- examples/cluster_data/data.tf
- examples/cluster_resource/resource.tf
- examples/eha_cluster_resource/resource.tf
- examples/eha_cluster_resource/variables.tf
- examples/ha_cluster_resource/resource.tf
- pkg/models/cluster.go
- pkg/provider/data_source_cluster.go
- pkg/provider/resource_cluster.go
This PR address two issues:
- Add resource example for EHA cluster
- Remove deprecated `replicas`
> Add EHA resource example and remove deprecated replicas

- README.md
- docs/index.md
- examples/provider/provider.tf
We standardized the provider block parameter `ba_bearer_token` and the env var name `BA_BEARER_TOKEN` in #84 , but 
I forgot to update the examples. 
This PR fixes the example and the documentation. 
Please review.
> docs: Correct the token variable name

- GNUmakefile
- README.md
- docs/resources/cluster.md
- docs/resources/region.md
- examples/data-sources/biganimal_cluster/provider.tf
- examples/data-sources/biganimal_region/provider.tf
- examples/resources/biganimal_cluster/eha/resource.tf
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/resource.tf
- examples/resources/biganimal_region/resource.tf
- main.go
* Adjust the HOSTNAME variable in GNUmakefile
* Remove the NAMESPACE, not needed
* Update the version to 0.1.0
* Update the source string in docs and examples
To test this change, please ensure that your `~/.terraformrc` file is similar to this:
```
provider_installation {
direct {
exclude = ["registry.terraform.io/EnterpriseDB/biganimal"]
}
filesystem_mirror {
path    = "/Users/<username>/.terraform.d/plugins"
include = ["EnterpriseDB/biganimal"]
}
}
```
This change will be merged later with #89. This terraformrc hack is needed until we publish the provider to the terraform registry.
> ci: Prepare for the release

- docs/resources/region.md
- templates/resources/region.md.tmpl
Because of [the create function of the RegionClient](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/pkg/api/region_client.go#L43) was shown as `Not Implemented`, I thought the creation of region resources was not implemented, that's why this disclaimer was added to the region resource documentation. 
However, `Create` for Region Resource simply [calls the Update function](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/pkg/provider/resource_region.go#L73). In a way, it makes sense because `Create` is `Updating a region with ACTIVE status`. 😅 
So, we do support the creation of regions, thanks to @kunliuedb for pointing that out! 
Updating the documentation accordingly. Please review.
> docs: Update docs, we actually support creating regions

- pkg/api/api.go
- pkg/api/cluster_client.go
- pkg/api/cluster_client_test.go
- pkg/api/region_client.go
- pkg/api/request.go
- pkg/provider/provider.go
to add `user-agent` to the HTTP header, make the following changes
- change `NewXxxClient(ba_bearer_token string, ba_api_uri string)` to ``NewXxxClient(api API)`
- change `doRequest()` called in each methods to `api.doReuqest()`
methods in `XxxClient` don't need to know `token` and `url`
> fix: Change api code structure for setting user-agent

- CHANGELOG.md
- GNUmakefile
- README.md
- docs/resources/cluster.md
- docs/resources/region.md
- examples/data-sources/biganimal_cluster/provider.tf
- examples/data-sources/biganimal_region/provider.tf
- examples/resources/biganimal_cluster/eha/resource.tf
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/resource.tf
- examples/resources/biganimal_region/resource.tf
We don't have an automated Changelog creation mechanism yet, that's why I wanted to start writing the Changelog.md manually for now, to start logging the changes.
This change updates the code to point to the new release. After merging this PR, I'll tag the `v0.1.1` version and start the release process. 
Please review.
> ci: Prepare for the release v0.1.1

- docs/data-sources/cluster.md
- examples/data-sources/biganimal_cluster/data-source.tf
- pkg/models/cluster.go
- pkg/provider/data_source_cluster.go
- pkg/provider/resource_cluster.go
With this change, the cluster data sources will be able to read the logs and metrics URLs.
Because they are computed fields, we're not reading values for those fields while creating a cluster. 
Please review.
> feat: Introduce logs_url and metrics_url to the biganimal_cluster resource/data-sources

- GNUmakefile
- README.md
- docs/resources/cluster.md
- docs/resources/region.md
- examples/data-sources/biganimal_cluster/provider.tf
- examples/data-sources/biganimal_region/provider.tf
- examples/resources/biganimal_cluster/eha/resource.tf
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/aws/resource.tf
- examples/resources/biganimal_cluster/single_node/azure/resource.tf
- examples/resources/biganimal_cluster/single_node/resource.tf
- examples/resources/biganimal_region/resource.tf
Release announcement for v0.1.2
```
v0.1.2 (January 10, 2023)
Enhancements:
* New fields are added to biganimal_cluster resource and data-sources
- csp_auth field for IAM authentication in AWS
- logs_url and metrics_url fields
* Various dependency updates
* GitHub Issue Templates are updated.
```
After the merge of this PR, I'm going to tag the release.
Please review.
> ci: Update the version strings for the 0.1.2 release.

- .envrc
- README.md
- docs/data-sources/cluster.md
- docs/data-sources/region.md
- docs/index.md
- docs/resources/cluster.md
- docs/resources/region.md
- examples/data-sources/biganimal_cluster/data-source.tf
- examples/data-sources/biganimal_region/data-source.tf
- examples/provider/provider.tf
- examples/resources/biganimal_cluster/eha/resource.tf
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/aws/resource.tf
- examples/resources/biganimal_cluster/single_node/azure/resource.tf
- examples/resources/biganimal_cluster/single_node/resource.tf
- examples/resources/biganimal_region/resource.tf
- go.mod
- pkg/api/cluster_client.go
- pkg/api/cluster_client_test.go
- pkg/api/region_client.go
- pkg/provider/data_source_cluster.go
- pkg/provider/data_source_region.go
- pkg/provider/provider.go
- pkg/provider/resource_cluster.go
- pkg/provider/resource_region.go
- pkg/provider/validators.go
- pkg/provider/validators_test.go
The PR looks good to go. 
I've created single_node clusters on AWS and Azure, EHA and HA clusters on AWS, and they all looked fine. 
Regions look good to go as well. 
With this PR, we introduce the `validators.go`. It's quite straightforward for a single field validation, which can be used later to accomplish the #85. 
It also contains a fix about the logs_url and metrics_url for the clusters. 
Please review.
> feat: Adapt to BigAnimal APIv3

- README.md
- examples/README.md
* Documentation for the `filesystem_mirror` way of provider development
* Add links for the AWS and Azure examples of the Single node. 
Please review.
> docs: Minor readme updates

- CONTRIBUTING.md
Let's include the Signing Commits documentation of GitHub in the Contribution doc as well. It's quite useful for those who haven't configured signed commits on their computer yet.
> docs: Enhance contribution documentation

- .gitignore
We're not using any vendor directory. In order to prevent adding it mistakenly, let's add vendor to gitignore. Please review.
> style: add vendor to gitignore

- .github/workflows/conventional-commits.yml
- .github/workflows/pre-commit.yml
- .github/workflows/spellcheck.yml
- .github/workflows/test.yml
Seen in @edbamolvyavahare 's [PR](https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/149), some workflows were running twice, both on push and pull_request. 
This PR should fix that. Please review.
From[ the documentation of pull_request event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request):
```
By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. 
```
Thus, I removed the event triggers for `pull_request` in the WFs.
> ci: Trigger workflows only once in PRs

- docs/resources/cluster.md
- docs/resources/region.md
- templates/resources/cluster.md.tmpl
- templates/resources/region.md.tmpl
When we're using templates, it's good to keep our code as close to [the upstream code](https://github.com/hashicorp/terraform-plugin-docs/blob/e8f8eb1f6dbb047551ceedd48e7810c6c6661d03/internal/provider/template.go#L217) as possible. 
The template doesn't work, when I use the 
```
{{ printf "{{tffile %q}}" .ExampleFile }}
```
I don't know why. That's why I kept on using 
```
{{ tffile .ExampleFile }}
```
Same goes for 
```
{{ codefile "shell" .ImportFile }}
```
(anyhow, we don't have the import functionality right now, see #88 for details)
> docs: Mostly whitespace changes in the docs

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- pkg/models/cluster.go
- pkg/provider/data_source_cluster.go
- pkg/provider/resource_cluster.go
These changes are taken out of #123, and they will fix #98. 
As explained [in this comment](https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/123#issuecomment-1412116738), they're breaking changes that demand a major bump. 
That's why I would like to keep this PR here and merge it before a major bump (unless we decide to break the API while we still don't have many active users that would be affected from this change)
> fix: Make allowedIpRanges and pgConfig TypeSet

- pkg/provider/data_source_fareplica.go
- pkg/provider/resource_fareplica.go
Those changes were forgotten when we merged #128. 
Faraway replicas can not be created with 0.4.1 as of now, so, this bug fix is important 😅 
Please review.
> fix: reflect TypeSet change to FAR as well

- DEVELOPMENT.md
Expanding the dev documentation. With this bash completion, the credentials from the BigAnimal CLI can be selected with tab completion. 
Please review.
> docs: Add bash completion for export_BA_env_vars

- pkg/models/project.go
Execute `terraform init` and `terraform plan` in the directory `examples/data-sources/biganimal_projects`. After running these commands, I encountered the following panic message.
```
panic: interface conversion: interface {} is *[]models.CloudProvider, not *schema.Set 
```
The issue occurs because the `CloudProviders` field of the `models.Project` is of pointer type, which cannot be parsed into the following `if` statement block.
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/field_writer_map.go#L300
so the following type of assertion will result in a panic 
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/field_writer_map.go#L346
> fix: Fixed datasource_project panic

- pkg/provider/provider.go
We're parsing the data to the `data` variable in this function, but then the return api.NewAPI function uses only the schema data.
In this case, the credentials are not fetched from the env vars for the tfprotov5 a.k.a. SDKv2 resources, such as biganimal_cluster.
because ba_bearer_token and ba_api_uri are not set for the Client, the calls fail, such as
Error: Post "/projects/prj_deadbeef012345667/clusters": unsupported protocol scheme ""
This change fixes the issue.
> fix: Fix a bug for credential data parsing in tfprotov5 resources

- docs/resources/cluster.md
- docs/resources/faraway_replica.md
- docs/resources/pgd.md
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/aws/resource.tf
- examples/resources/biganimal_cluster/single_node/azure/resource.tf
- examples/resources/biganimal_cluster/single_node/resource.tf
- examples/resources/biganimal_faraway_replica/cluster_and_faraway_replica/resource.tf
- examples/resources/biganimal_pgd/aws/data_group/resource.tf
- examples/resources/biganimal_pgd/aws/data_groups_with_witness_group/resource.tf
- examples/resources/biganimal_pgd/azure/data_group/resource.tf
- examples/resources/biganimal_pgd/azure/data_groups_with_witness_group/resource.tf
- pkg/provider/resource_cluster_test.go
- pkg/provider/resource_pgd_test.go
Not only the examples, but also the acceptance test files are updated. 
<s>Testing this change now</s> This change is tested in the following scenarios: 
-  Single Node Cluster on AWS
-  Single Node Cluster on Azure
-  HA cluster on Azure
-  Cluster and Faraway Replica from that cluster
-  AWS 1 DG
-  AWS 2 DG 1 WG
-  Azure 1 DG
-  Azure 2 DG 1 WG
Please review.
> docs: Update EPAS examples to use pg_version 15

- pkg/provider/resource_cluster.go
We also need the Unknown PlanModifier, in case it's not provided in the config
Fixes #322. 
Please review.
> fix: Set backup_retention_period also as computed

- docs/resources/cluster.md
- examples/README.md
- examples/resources/biganimal_cluster/single_node/bah_aws/resource.tf
- examples/resources/biganimal_cluster/single_node/bah_gcp/resource.tf
- pkg/provider/resource_cluster.go
Single Node cluster examples are added. 
Please review.
> feat: Add BigAnimal Hosted support for biganimal_cluster resource

- pkg/models/pgd/terraform/cluster_architecture.go
- pkg/plan_modifier/data_group_custom_diff.go
- pkg/provider/data_source_pgd.go
- pkg/provider/resource_pgd.go
PGD add data group expects cluster arch witness nodes unknowns. This is reflect a change from the API
> fix: PGD add group state inconsistent bug

- pkg/plan_modifier/data_group_custom_diff.go
- pkg/provider/data_source_pgd.go
- pkg/provider/resource_cluster.go
- pkg/provider/resource_pgd.go
I have removed default pg configs in the response so only user custom pg configs show like:
before it use to have a lot more elements because of the defaults. This is a more future solution as defaults can be added/removed from the backend in future and cause a mismatch in our plan and response state.
> fix: pg config bug

- docs/data-sources/analytics_cluster.md
- docs/data-sources/cluster.md
- docs/data-sources/faraway_replica.md
- docs/resources/analytics_cluster.md
- docs/resources/cluster.md
- docs/resources/faraway_replica.md
- docs/resources/pgd.md
- examples/resources/biganimal_cluster/ha/resource.tf
- examples/resources/biganimal_cluster/single_node/aws/resource.tf
- examples/resources/biganimal_pgd/aws/data_group/resource.tf
- examples/resources/biganimal_pgd/aws/data_groups_with_witness_group/resource.tf
- pkg/plan_modifier/data_group_custom_diff_test.go
- pkg/provider/data_source_analytics_cluster.go
- pkg/provider/data_source_cluster.go
- pkg/provider/data_source_fareplica.go
- pkg/provider/resource_analytics_cluster.go
- pkg/provider/resource_cluster.go
- pkg/provider/resource_cluster_test.go
- pkg/provider/resource_fareplica.go
This PR is intended to update the cluster provisioning options in AWS biganimal TF provider to use the 6 series instead of the 5 series.
> chore: Update AWS instance type example to use series 6
